import {useEffect,useMemo,useState} from 'react';
import {supabase} from '../lib/supabase';
import {BarChart,Bar,XAxis,YAxis,Tooltip,ResponsiveContainer,LineChart,Line,CartesianGrid} from 'recharts';

export default function Analytics(){
 const [bookings,setBookings]=useState<any[]>([]); const [payments,setPayments]=useState<any[]>([]); const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{const [{data:b},{data:p}]=await Promise.all([supabase.from('bookings').select('booking_date,final_amount,booking_status'),supabase.from('payments').select('amount,status,created_at')]);setBookings(b||[]);setPayments(p||[]);setLoading(false)})()},[]);
 const days=useMemo(()=>{const m=new Map<string,{date:string,bookings:number,revenue:number}>();bookings.forEach(x=>{const k=x.booking_date;const r=m.get(k)||{date:k,bookings:0,revenue:0};r.bookings++;if(x.booking_status!=='CANCELLED')r.revenue+=Number(x.final_amount||0);m.set(k,r)});return [...m.values()].sort((a,b)=>a.date.localeCompare(b.date)).slice(-14)},[bookings]);
 const revenue=payments.filter(x=>x.status==='SUCCESS').reduce((a,x)=>a+Number(x.amount||0),0);
 return <main className="mx-auto max-w-6xl px-5 py-12"><p className="accent text-sm font-bold uppercase tracking-[.2em]">Live metrics</p><h1 className="mt-2 text-4xl font-black">Analytics.</h1>{loading?<div className="card mt-8 p-8">Loading analytics…</div>:<><div className="mt-8 grid gap-4 sm:grid-cols-3"><div className="card p-5"><p className="text-sm text-slate-500">Bookings</p><b className="text-3xl">{bookings.length}</b></div><div className="card p-5"><p className="text-sm text-slate-500">Successful revenue</p><b className="text-3xl">₹{revenue.toFixed(0)}</b></div><div className="card p-5"><p className="text-sm text-slate-500">Cancellations</p><b className="text-3xl">{bookings.filter(x=>x.booking_status==='CANCELLED').length}</b></div></div><div className="card mt-8 p-5"><h2 className="mb-5 text-xl font-bold">Daily bookings & revenue</h2><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={days}><CartesianGrid strokeDasharray="3 3" opacity={.12}/><XAxis dataKey="date"/><YAxis/><Tooltip/><Line type="monotone" dataKey="bookings" strokeWidth={2}/><Line type="monotone" dataKey="revenue" strokeWidth={2}/></LineChart></ResponsiveContainer></div></div><div className="card mt-8 p-5"><h2 className="mb-5 text-xl font-bold">Booking volume</h2><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={days}><XAxis dataKey="date"/><YAxis/><Tooltip/><Bar dataKey="bookings"/></BarChart></ResponsiveContainer></div></div></>}</main>
}
