import {FormEvent,useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {Bell,CheckCircle2,Heart,Star,Ticket,Trash2} from 'lucide-react';
import {supabase} from '../lib/supabase';
import {getSession} from '../lib/auth';

type FavoriteRow={user_id:string;turf_id:string;created_at:string;turfs:{id:string;name:string;city:string|null;cover_image_url:string|null;rating:number;review_count:number;starting_price:number}|null};
type NotificationRow={id:string;type:string;title:string;message:string;read_at:string|null;created_at:string};

export function Favourites(){
  const [rows,setRows]=useState<FavoriteRow[]>([]);const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');const navigate=useNavigate();
  async function load(){setLoading(true);setError('');try{const {data:session,error:sessionError}=await getSession();if(sessionError)throw sessionError;if(!session.session){navigate('/login');return}const {data,error}=await supabase.from('favourites').select('user_id,turf_id,created_at,turfs(id,name,city,cover_image_url,rating,review_count,starting_price)').eq('user_id',session.session.user.id).order('created_at',{ascending:false});if(error)throw error;setRows((data||[]) as unknown as FavoriteRow[])}catch(err){setError(err instanceof Error?err.message:'Unable to load saved turfs.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function remove(turfId:string){setError('');const {error}=await supabase.from('favourites').delete().eq('turf_id',turfId);if(error){setError(error.message);return}setRows(current=>current.filter(row=>row.turf_id!==turfId))}
  return <main className="mx-auto max-w-6xl px-5 py-12"><p className="accent text-sm font-bold uppercase tracking-[.2em]">Saved turfs</p><h1 className="mt-2 text-4xl font-black">Your favourites</h1>{error&&<p role="alert" className="mt-5 rounded-xl bg-red-400/10 p-4 text-sm text-red-200">{error}</p>}{loading?<div className="card mt-8 p-10 text-center text-slate-500">Loading favourites…</div>:rows.length===0?<div className="card mt-8 p-10 text-center text-slate-500"><Heart className="mx-auto"/><p className="mt-3">No favourites saved yet.</p><Link to="/explore" className="mt-4 inline-block accent">Explore turfs →</Link></div>:<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{rows.map(row=>row.turfs&&<article className="card overflow-hidden" key={row.turf_id}><Link to={`/turf/${row.turf_id}`} className="block h-44 bg-slate-900">{row.turfs.cover_image_url?<img src={row.turfs.cover_image_url} alt={row.turfs.name} className="h-full w-full object-cover"/>:<span className="grid h-full place-items-center text-slate-600">Venue photo unavailable</span>}</Link><div className="p-5"><div className="flex justify-between gap-3"><div><Link to={`/turf/${row.turf_id}`} className="text-lg font-bold hover:text-lime-300">{row.turfs.name}</Link><p className="text-sm text-slate-400">{row.turfs.city||'Location unavailable'}</p></div><button aria-label={`Remove ${row.turfs.name} from favourites`} onClick={()=>void remove(row.turf_id)} className="text-slate-500 hover:text-red-300"><Trash2 size={18}/></button></div><p className="mt-4 text-sm"><Star size={15} className="mr-1 inline accent"/> {Number(row.turfs.rating||0).toFixed(1)} · ₹{Number(row.turfs.starting_price||0).toFixed(0)} / slot</p><Link to={`/book/${row.turf_id}`} className="accent-bg mt-4 block rounded-xl py-3 text-center text-sm font-bold">Book this turf</Link></div></article>)}</div>}</main>
}

export function Notifications(){
  const [rows,setRows]=useState<NotificationRow[]>([]);const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');const navigate=useNavigate();
  async function load(){setLoading(true);setError('');try{const {data:session,error:sessionError}=await getSession();if(sessionError)throw sessionError;if(!session.session){navigate('/login');return}const {data,error}=await supabase.from('notifications').select('id,type,title,message,read_at,created_at').eq('user_id',session.session.user.id).order('created_at',{ascending:false});if(error)throw error;setRows(data||[])}catch(err){setError(err instanceof Error?err.message:'Unable to load notifications.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[]);
  async function read(id:string){const {error}=await supabase.rpc('mark_notification_read',{p_id:id});if(error){setError(error.message);return}setRows(current=>current.map(row=>row.id===id?{...row,read_at:new Date().toISOString()}:row))}
  async function markAllRead(){const unread=rows.filter(row=>!row.read_at);for(const row of unread){const {error}=await supabase.rpc('mark_notification_read',{p_id:row.id});if(error){setError(error.message);return}}setRows(current=>current.map(row=>({...row,read_at:row.read_at||new Date().toISOString()})))}
  return <main className="mx-auto max-w-4xl px-5 py-12"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="accent text-sm font-bold uppercase tracking-[.2em]">Updates</p><h1 className="mt-2 text-4xl font-black">Notifications</h1></div>{rows.some(row=>!row.read_at)&&<button onClick={()=>void markAllRead()} className="rounded-xl border border-white/10 px-4 py-2 text-sm">Mark all read</button>}</div>{error&&<p role="alert" className="mt-5 rounded-xl bg-red-400/10 p-4 text-sm text-red-200">{error}</p>}{loading?<p className="mt-8 text-slate-500">Loading notifications…</p>:<div className="mt-8 space-y-3">{rows.map(notification=><article key={notification.id} className={`card w-full p-5 transition ${notification.read_at?'opacity-60':'ring-1 ring-lime-400/20'}`}><div className="flex gap-4"><Bell className="accent mt-1 shrink-0" size={20}/><div className="flex-1"><div className="flex justify-between gap-3"><b>{notification.title}</b>{!notification.read_at&&<span className="text-xs accent">NEW</span>}</div><p className="mt-1 text-sm text-slate-400">{notification.message}</p><div className="mt-2 flex items-center justify-between gap-3"><p className="text-xs text-slate-600">{notification.type.replaceAll('_',' ')} · {new Date(notification.created_at).toLocaleString()}</p>{!notification.read_at&&<button onClick={()=>void read(notification.id)} className="text-xs font-semibold accent">Mark read</button>}</div></div></div></article>)}{!rows.length&&<div className="card p-10 text-center text-slate-500">No notifications.</div>}</div>}</main>
}

export function Coupons(){
  const [code,setCode]=useState('');const [amount,setAmount]=useState('');const [result,setResult]=useState<{valid:boolean;message:string;discount?:number}|null>(null);
  const [error,setError]=useState('');const [loading,setLoading]=useState(false);
  async function check(event:FormEvent){event.preventDefault();setError('');setResult(null);const value=Number(amount);if(!code.trim()||!Number.isFinite(value)||value<=0){setError('Enter a coupon code and a valid booking amount.');return}setLoading(true);try{const {data,error}=await supabase.rpc('validate_coupon',{p_code:code.trim(),p_amount:value});if(error)throw error;setResult(data as typeof result)}catch(err){setError(err instanceof Error?err.message:'Unable to validate this coupon.')}finally{setLoading(false)}}
  return <main className="mx-auto max-w-2xl px-5 py-12"><p className="accent text-sm font-bold uppercase tracking-[.2em]">Promotions</p><h1 className="mt-2 text-4xl font-black">Check a coupon</h1><form onSubmit={check} className="card mt-8 space-y-4 p-6"><label className="block text-sm text-slate-400">Coupon code<input required value={code} onChange={e=>{setCode(e.target.value.toUpperCase());setResult(null)}} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-3 outline-none" placeholder="Enter code"/></label><label className="block text-sm text-slate-400">Booking amount<input required min="1" step="0.01" type="number" value={amount} onChange={e=>{setAmount(e.target.value);setResult(null)}} className="mt-2 w-full rounded-xl border border-white/10 bg-white/5 p-3 outline-none" placeholder="₹ amount"/></label>{error&&<p role="alert" className="text-sm text-red-300">{error}</p>}<button disabled={loading} className="accent-bg w-full rounded-xl px-5 py-3 font-bold disabled:opacity-50"><Ticket className="mr-2 inline" size={18}/>{loading?'Checking…':'Check coupon'}</button>{result&&<div role="status" className={`rounded-xl p-4 text-sm ${result.valid?'bg-lime-400/10 text-lime-200':'bg-red-400/10 text-red-200'}`}>{result.valid&&<CheckCircle2 className="mr-2 inline" size={18}/ >}{result.message}{result.valid&&` · Discount ₹${Number(result.discount||0).toFixed(2)}`}</div>}</form></main>
}

export function ReviewForm({bookingId,turfId,onDone}:{bookingId:string;turfId:string;onDone?:()=>void}){
  const [rating,setRating]=useState(5);const [text,setText]=useState('');const [saving,setSaving]=useState(false);
  const [eligible,setEligible]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [saved,setSaved]=useState(false);
  useEffect(()=>{let active=true;async function check(){try{const {data,error}=await supabase.from('bookings').select('id').eq('id',bookingId).eq('turf_id',turfId).eq('booking_status','COMPLETED').maybeSingle();if(error)throw error;if(active)setEligible(!!data)}catch(err){if(active)setError(err instanceof Error?err.message:'Unable to verify booking review eligibility.')}finally{if(active)setLoading(false)}}void check();return()=>{active=false}},[bookingId,turfId]);
  async function save(){setError('');setSaving(true);try{if(!eligible)throw new Error('A review can be submitted only after this booking is completed.');const {data:session,error:sessionError}=await getSession();if(sessionError)throw sessionError;if(!session.session)throw new Error('Please sign in to submit a review.');const {error}=await supabase.from('reviews').upsert({booking_id:bookingId,turf_id:turfId,customer_id:session.session.user.id,rating,review_text:text.trim()||null},{onConflict:'booking_id'});if(error)throw error;setSaved(true);onDone?.()}catch(err){setError(err instanceof Error?err.message:'Unable to submit this review.')}finally{setSaving(false)}}
  if(loading)return <div className="card p-5 text-sm text-slate-500">Checking completed booking…</div>;
  if(!eligible)return <div className="card p-5 text-sm text-slate-500">{error||'Reviews are available after a verified booking is completed.'}</div>;
  if(saved)return <div role="status" className="card p-5 text-sm text-lime-200">Thank you. Your verified review was submitted.</div>;
  return <div className="card p-6"><h3 className="text-xl font-bold">Rate your completed game</h3><div className="mt-4 flex gap-2" role="group" aria-label="Rating">{[1,2,3,4,5].map(value=><button type="button" key={value} aria-label={`${value} star${value===1?'':'s'}`} aria-pressed={rating===value} onClick={()=>setRating(value)}><Star size={25} className={value<=rating?'fill-current accent':'text-slate-600'}/></button>)}</div><textarea maxLength={2000} value={text} onChange={e=>setText(e.target.value)} className="mt-4 min-h-28 w-full rounded-xl border border-white/10 bg-white/5 p-3 outline-none" placeholder="How was the turf?"/>{error&&<p role="alert" className="mt-3 text-sm text-red-300">{error}</p>}<button disabled={saving} onClick={()=>void save()} className="accent-bg mt-4 rounded-xl px-5 py-3 font-bold disabled:opacity-50">{saving?'Saving…':'Submit review'}</button></div>
}
