create extension if not exists pgcrypto;
create type public.app_role as enum ('CUSTOMER','OWNER','STAFF','ADMIN');
create type public.approval_status as enum ('PENDING','APPROVED','REJECTED');
create type public.turf_status as enum ('ACTIVE','INACTIVE','SUSPENDED');
create type public.booking_status as enum ('PENDING','CONFIRMED','CANCELLED','COMPLETED','NO_SHOW','RESCHEDULED');
create type public.slot_status as enum ('AVAILABLE','TEMPORARILY_LOCKED','BOOKED','BLOCKED','MAINTENANCE');
create type public.payment_status as enum ('PENDING','PROCESSING','SUCCESS','FAILED','REFUNDED','PARTIALLY_REFUNDED');
create type public.payment_method as enum ('UPI','CARD','NET_BANKING','PAY_AT_TURF');
create type public.checkin_status as enum ('NOT_CHECKED_IN','CHECKED_IN','CHECKED_OUT');
create type public.ticket_status as enum ('OPEN','IN_REVIEW','RESOLVED','REJECTED');

create table public.profiles(id uuid primary key references auth.users(id) on delete cascade, full_name text, email text, phone text, avatar_url text, status text not null default 'ACTIVE', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.user_roles(user_id uuid primary key references public.profiles(id) on delete cascade, role public.app_role not null default 'CUSTOMER', created_at timestamptz not null default now());
create table public.owner_profiles(user_id uuid primary key references public.profiles(id) on delete cascade,business_name text,business_address text,verification_status public.approval_status not null default 'PENDING');
create table public.staff_profiles(user_id uuid primary key references public.profiles(id) on delete cascade,owner_id uuid references public.profiles(id) on delete set null,phone text,status text not null default 'ACTIVE');
create table public.customer_profiles(user_id uuid primary key references public.profiles(id) on delete cascade,address text,preferred_sports text[] default '{}');

create table public.sports(id uuid primary key default gen_random_uuid(),name text unique not null,slug text unique not null,active boolean not null default true,created_at timestamptz not null default now());
create table public.facilities(id uuid primary key default gen_random_uuid(),name text unique not null,active boolean not null default true,created_at timestamptz not null default now());
create table public.turfs(id uuid primary key default gen_random_uuid(),owner_id uuid not null references public.profiles(id) on delete restrict,name text not null,description text,address text,area text,city text,latitude numeric,longitude numeric,contact_number text,opening_time time not null,closing_time time not null,turf_type text not null,indoor boolean not null default false,status public.turf_status not null default 'INACTIVE',approval_status public.approval_status not null default 'PENDING',cancellation_policy jsonb not null default '{}'::jsonb,rules text,cover_image_url text,rating numeric(3,2) not null default 0,review_count integer not null default 0,starting_price numeric(12,2) not null default 0,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.turf_images(id uuid primary key default gen_random_uuid(),turf_id uuid not null references public.turfs(id) on delete cascade,url text not null,sort_order int not null default 0,is_primary boolean not null default false,created_at timestamptz not null default now());
create table public.turf_sports(turf_id uuid references public.turfs(id) on delete cascade,sport_id uuid references public.sports(id) on delete cascade,primary key(turf_id,sport_id));
create table public.turf_facilities(turf_id uuid references public.turfs(id) on delete cascade,facility_id uuid references public.facilities(id) on delete cascade,primary key(turf_id,facility_id));
create table public.slot_templates(id uuid primary key default gen_random_uuid(),turf_id uuid not null references public.turfs(id) on delete cascade,sport_id uuid references public.sports(id) on delete set null,start_time time not null,end_time time not null,price numeric(12,2) not null,active boolean not null default true,created_at timestamptz not null default now());
create table public.blocked_slots(id uuid primary key default gen_random_uuid(),turf_id uuid not null references public.turfs(id) on delete cascade,booking_date date not null,start_time time not null,end_time time not null,reason text,created_by uuid references public.profiles(id) on delete set null,created_at timestamptz not null default now());
create table public.maintenance_records(id uuid primary key default gen_random_uuid(),turf_id uuid not null references public.turfs(id) on delete cascade,start_at timestamptz not null,end_at timestamptz not null,reason text,created_by uuid references public.profiles(id) on delete set null,status text not null default 'ACTIVE',created_at timestamptz not null default now());
create table public.bookings(id uuid primary key default gen_random_uuid(),customer_id uuid not null references public.profiles(id) on delete restrict,turf_id uuid not null references public.turfs(id) on delete restrict,sport_id uuid references public.sports(id) on delete set null,booking_date date not null,start_time time not null,end_time time not null,duration_minutes integer not null,base_price numeric(12,2) not null,discount numeric(12,2) not null default 0,tax numeric(12,2) not null default 0,final_amount numeric(12,2) not null,coupon_id uuid,booking_status public.booking_status not null default 'PENDING',payment_status public.payment_status not null default 'PENDING',qr_token_hash text unique,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.booking_slot_locks(id uuid primary key default gen_random_uuid(),turf_id uuid not null references public.turfs(id) on delete cascade,booking_date date not null,start_time time not null,end_time time not null,locked_by uuid not null references public.profiles(id) on delete cascade,expires_at timestamptz not null,created_at timestamptz not null default now());
create table public.payments(id uuid primary key default gen_random_uuid(),booking_id uuid not null unique references public.bookings(id) on delete cascade,amount numeric(12,2) not null,method public.payment_method not null,status public.payment_status not null default 'PENDING',transaction_id text unique,gateway_reference text,paid_at timestamptz,created_at timestamptz not null default now());
create table public.refunds(id uuid primary key default gen_random_uuid(),booking_id uuid not null references public.bookings(id) on delete cascade,amount numeric(12,2) not null,reason text,status text not null default 'PENDING',refund_transaction_id text,requested_at timestamptz not null default now(),completed_at timestamptz);
create table public.favourites(user_id uuid references public.profiles(id) on delete cascade,turf_id uuid references public.turfs(id) on delete cascade,created_at timestamptz not null default now(),primary key(user_id,turf_id));
create table public.reviews(id uuid primary key default gen_random_uuid(),booking_id uuid not null unique references public.bookings(id) on delete cascade,turf_id uuid not null references public.turfs(id) on delete cascade,customer_id uuid not null references public.profiles(id) on delete cascade,rating int not null check(rating between 1 and 5),review_text text,image_url text,approved boolean not null default true,created_at timestamptz not null default now());
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,type text not null,title text not null,message text not null,read_at timestamptz,created_at timestamptz not null default now());
create table public.coupons(id uuid primary key default gen_random_uuid(),owner_id uuid references public.profiles(id) on delete set null,code text unique not null,description text,discount_type text not null check(discount_type in ('FLAT','PERCENTAGE')),discount_value numeric(12,2) not null,min_booking_amount numeric(12,2) default 0,max_discount numeric(12,2),start_at timestamptz not null,expires_at timestamptz not null,usage_limit int,per_user_limit int,active boolean not null default true,created_at timestamptz not null default now());
create table public.coupon_usages(id uuid primary key default gen_random_uuid(),coupon_id uuid not null references public.coupons(id) on delete cascade,user_id uuid not null references public.profiles(id) on delete cascade,booking_id uuid not null references public.bookings(id) on delete cascade,used_at timestamptz not null default now(),unique(coupon_id,booking_id));
create table public.teams(id uuid primary key default gen_random_uuid(),captain_id uuid not null references public.profiles(id) on delete cascade,name text not null,logo_url text,created_at timestamptz not null default now());
create table public.team_members(team_id uuid references public.teams(id) on delete cascade,user_id uuid references public.profiles(id) on delete cascade,status text not null default 'ACTIVE',created_at timestamptz not null default now(),primary key(team_id,user_id));
create table public.team_bookings(team_id uuid references public.teams(id) on delete cascade,booking_id uuid references public.bookings(id) on delete cascade,primary key(team_id,booking_id));
create table public.split_payments(id uuid primary key default gen_random_uuid(),booking_id uuid not null references public.bookings(id) on delete cascade,member_id uuid not null references public.profiles(id) on delete cascade,amount_assigned numeric(12,2) not null,amount_paid numeric(12,2) not null default 0,status public.payment_status not null default 'PENDING',paid_at timestamptz);
create table public.membership_plans(id uuid primary key default gen_random_uuid(),name text not null,price numeric(12,2) not null,duration_days int not null,discount_percentage numeric(5,2) not null default 0,booking_benefits text,cancellation_benefits text,active boolean not null default true,created_at timestamptz not null default now());
create table public.user_memberships(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,plan_id uuid not null references public.membership_plans(id) on delete restrict,start_date date not null,end_date date not null,status text not null default 'ACTIVE',created_at timestamptz not null default now());
create table public.check_ins(id uuid primary key default gen_random_uuid(),booking_id uuid not null unique references public.bookings(id) on delete cascade,staff_id uuid references public.profiles(id) on delete set null,status public.checkin_status not null default 'NOT_CHECKED_IN',checked_in_at timestamptz,checked_out_at timestamptz);
create table public.tournaments(id uuid primary key default gen_random_uuid(),owner_id uuid references public.profiles(id) on delete set null,turf_id uuid references public.turfs(id) on delete set null,sport_id uuid references public.sports(id) on delete set null,name text not null,start_date date not null,end_date date not null,registration_deadline date,entry_fee numeric(12,2) default 0,max_teams int,prize_info text,rules text,description text,banner_image_url text,status text not null default 'DRAFT',created_at timestamptz not null default now());
create table public.support_tickets(id uuid primary key default gen_random_uuid(),user_id uuid not null references public.profiles(id) on delete cascade,booking_id uuid references public.bookings(id) on delete set null,category text not null,subject text not null,description text not null,attachment_url text,priority text not null default 'NORMAL',status public.ticket_status not null default 'OPEN',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.support_messages(id uuid primary key default gen_random_uuid(),ticket_id uuid not null references public.support_tickets(id) on delete cascade,sender_id uuid not null references public.profiles(id) on delete cascade,message text not null,created_at timestamptz not null default now());
create table public.invoices(id uuid primary key default gen_random_uuid(),booking_id uuid not null unique references public.bookings(id) on delete cascade,invoice_number text unique not null,issued_at timestamptz not null default now(),pdf_url text);
create table public.audit_logs(id uuid primary key default gen_random_uuid(),actor_id uuid references public.profiles(id) on delete set null,action text not null,entity text not null,entity_id uuid,old_value jsonb,new_value jsonb,created_at timestamptz not null default now());
create table public.system_settings(key text primary key,value jsonb not null,updated_at timestamptz not null default now());

create index turfs_owner_idx on public.turfs(owner_id); create index turfs_search_idx on public.turfs(city,area); create index bookings_customer_idx on public.bookings(customer_id); create index bookings_turf_date_idx on public.bookings(turf_id,booking_date); create index bookings_status_idx on public.bookings(booking_status); create index payments_status_idx on public.payments(status); create index notifications_user_idx on public.notifications(user_id,read_at); create index locks_expiry_idx on public.booking_slot_locks(expires_at);

create or replace function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles where user_id=auth.uid() and role='ADMIN'); $$;
create or replace function public.has_role(r public.app_role) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.user_roles where user_id=auth.uid() and role=r); $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name','')); insert into public.user_roles(user_id,role) values(new.id,'CUSTOMER'); insert into public.customer_profiles(user_id) values(new.id); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

create or replace function public.create_booking_atomic(p_turf_id uuid,p_sport_id uuid,p_booking_date date,p_start time,p_end time,p_duration int,p_amount numeric) returns uuid language plpgsql security definer set search_path=public as $$ declare v_id uuid; begin if auth.uid() is null then raise exception 'Not authenticated'; end if; if exists(select 1 from public.bookings where turf_id=p_turf_id and booking_date=p_booking_date and start_time < p_end and end_time > p_start and booking_status in ('PENDING','CONFIRMED','RESCHEDULED')) then raise exception 'SLOT_UNAVAILABLE'; end if; if exists(select 1 from public.blocked_slots where turf_id=p_turf_id and booking_date=p_booking_date and start_time < p_end and end_time > p_start) then raise exception 'SLOT_BLOCKED'; end if; if exists(select 1 from public.maintenance_records where turf_id=p_turf_id and start_at < (p_booking_date+p_end) and end_at > (p_booking_date+p_start) and status='ACTIVE') then raise exception 'SLOT_MAINTENANCE'; end if; insert into public.bookings(customer_id,turf_id,sport_id,booking_date,start_time,end_time,duration_minutes,base_price,final_amount,booking_status) values(auth.uid(),p_turf_id,p_sport_id,p_booking_date,p_start,p_end,p_duration,p_amount,p_amount,'PENDING') returning id into v_id; return v_id; end; $$;

alter table public.profiles enable row level security; alter table public.user_roles enable row level security; alter table public.customer_profiles enable row level security; alter table public.owner_profiles enable row level security; alter table public.staff_profiles enable row level security; alter table public.turfs enable row level security; alter table public.turf_images enable row level security; alter table public.sports enable row level security; alter table public.facilities enable row level security; alter table public.turf_sports enable row level security; alter table public.turf_facilities enable row level security; alter table public.bookings enable row level security; alter table public.payments enable row level security; alter table public.refunds enable row level security; alter table public.favourites enable row level security; alter table public.reviews enable row level security; alter table public.notifications enable row level security; alter table public.support_tickets enable row level security; alter table public.support_messages enable row level security; alter table public.audit_logs enable row level security;
create policy "public approved turfs" on public.turfs for select using(status='ACTIVE' and approval_status='APPROVED');
create policy "users own profile" on public.profiles for select using(id=auth.uid() or public.is_admin()); create policy "users update own profile" on public.profiles for update using(id=auth.uid() or public.is_admin());
create policy "own roles" on public.user_roles for select using(user_id=auth.uid() or public.is_admin());
create policy "own customer profile" on public.customer_profiles for all using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
create policy "owner manages own turfs" on public.turfs for all using(owner_id=auth.uid() or public.is_admin()) with check(owner_id=auth.uid() or public.is_admin());
create policy "customer own bookings" on public.bookings for select using(customer_id=auth.uid() or public.is_admin() or exists(select 1 from public.turfs t where t.id=bookings.turf_id and t.owner_id=auth.uid()));
create policy "customer creates booking" on public.bookings for insert with check(customer_id=auth.uid());
create policy "customer updates booking" on public.bookings for update using(customer_id=auth.uid() or public.is_admin() or exists(select 1 from public.turfs t where t.id=bookings.turf_id and t.owner_id=auth.uid()));
create policy "own payments" on public.payments for select using(public.is_admin() or exists(select 1 from public.bookings b where b.id=payments.booking_id and (b.customer_id=auth.uid() or exists(select 1 from public.turfs t where t.id=b.turf_id and t.owner_id=auth.uid()))));
create policy "own favourites" on public.favourites for all using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
create policy "approved reviews public" on public.reviews for select using(approved=true or customer_id=auth.uid() or public.is_admin()); create policy "customer reviews" on public.reviews for insert with check(customer_id=auth.uid());
create policy "own notifications" on public.notifications for select using(user_id=auth.uid() or public.is_admin()); create policy "own notification update" on public.notifications for update using(user_id=auth.uid() or public.is_admin());
create policy "own tickets" on public.support_tickets for all using(user_id=auth.uid() or public.is_admin()) with check(user_id=auth.uid() or public.is_admin());
create policy "ticket messages" on public.support_messages for select using(public.is_admin() or exists(select 1 from public.support_tickets t where t.id=ticket_id and t.user_id=auth.uid()));
create policy "audit admin" on public.audit_logs for select using(public.is_admin());

insert into public.sports(name,slug) values ('Football','football'),('Cricket','cricket'),('Badminton','badminton'),('Basketball','basketball'),('Volleyball','volleyball'),('Tennis','tennis'),('Box Cricket','box-cricket') on conflict do nothing;
insert into public.facilities(name) values ('Parking'),('Washroom'),('Changing Room'),('Drinking Water'),('Flood Lights'),('Seating'),('CCTV'),('First Aid'),('Locker'),('Equipment Rental'),('Wi-Fi'),('Shower'),('Reception') on conflict do nothing;
insert into public.system_settings(key,value) values ('booking_hold_minutes','10'),('tax_percentage','0'),('minimum_booking_minutes','60'),('maximum_booking_minutes','180') on conflict do nothing;
